#!/usr/bin/env bash
#Configure Nginx server so that /redirect_me is redirecting to another page.

server_name_oldstr="server_name _;"
server_name_newstr="server_name _;\n\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"

error_page_oldstr="=404;"
error_page_newstr="@oui_oui_baguette;\n\t}\n\n\tlocation @oui_oui_baguette {\n\t\tdefault_type text/html;\n\t\treturn 404 \"Ceci n'est pas une page\";"
error_page_str="error_page 404 /not_found_page_404.html;\n\tlocation = /not_found_page_404.html {\n\t\troot /var/www/html;\n\t}"

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
         sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# starting nginx service
sudo service nginx start

# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default configuration
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bckp

# Update Nginx configuration for server_name
sudo sed -i "/$server_name_oldstr/c$server_name_newstr" /etc/nginx/sites-available/default

# Update Nginx configuration for error_page
sudo sed -i "/$error_page_oldstr/c$error_page_newstr\n\n\t$error_page_str" /etc/nginx/sites-available/default

# Restarting nginx
sudo service nginx restart

echo -e "\nCompleted. ✅\n"
