#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.

nginx_config_file="/etc/nginx/sites-available/default"
backup_suffix=".bckp"
custom_404_page_path="/var/www/html/not_found_page_404.html"

# Update Nginx configuration for redirect_me
oldstr="server_name _;"
newstr="server_name _;\n\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
         sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# Starting Nginx service
sudo service nginx start

# Allowing Nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default configuration to stay working safe
sudo cp "$nginx_config_file" "$nginx_config_file$backup_suffix"

# Update Nginx configuration for redirect_me
sudo sed -i "/$oldstr/c$newstr" "$nginx_config_file"

# Configure custom 404 page
echo -e "\nConfiguring custom 404 page.\n"
sudo sh -c "echo -e '$custom_404_page' > /var/www/html/custom_404.html"

# Update Nginx configuration for custom 404 page
sudo bash -c "cat <<EOL >> $nginx_config_file

error_page 404 /custom_404.html;
location = /custom_404.html {
    root /var/www/html;
    internal;
}
EOL"

# Restarting Nginx so the changes can take effect
sudo service nginx restart

echo -e "\nCompleted. ✅\n" 
